# Generated by Django 3.2.12 on 2022-05-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('parameterID', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('regionID', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('weatherdataID', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(max_length=100, unique=True)),
                ('month_season', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField()),
                ('region_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='met_office.regions')),
            ],
        ),
        migrations.CreateModel(
            name='ParametersValues',
            fields=[
                ('parametervalueID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('parameter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='met_office.parameters')),
                ('weather_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='met_office.weatherdata')),
            ],
        ),
    ]
