# Generated by Django 3.2.12 on 2022-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('met_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='month_season',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='year',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='parametersvalues',
            unique_together={('parameter_id', 'weather_id')},
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('year', 'month_season', 'region_id')},
        ),
    ]
